name: deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment name to use when triggered manually'
        required: false

jobs:
  determine-env:
    name: Prepare environment
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.determine_env.outputs.env_name }}
    steps:
      - id: determine_env
        name: Determine environment
        run: |
          echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            INPUT_ENV="${{ github.event.inputs.environment }}"
            if [ -n "${INPUT_ENV}" ]; then
              echo "env_name=${INPUT_ENV}" >> $GITHUB_OUTPUT
            else
              echo "env_name=manual" >> $GITHUB_OUTPUT
            fi
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            ENV=${TAG%%@*}
            echo "env_name=${ENV}" >> $GITHUB_OUTPUT
          else
            echo "env_name=unknown" >> $GITHUB_OUTPUT
          fi
  
  prepare-variables:
    needs: determine-env
    name: variable_setup
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-env.outputs.env_name }}
    outputs:
      env_variable: ${{ steps.set_env.outputs.env_variable }}
      env_secret: ${{ steps.set_env.outputs.env_secret }}
    steps:
      - id: set_env
        name: Set environment variable
        run: |
          echo "Setting environment variable based on environment: ${{ needs.determine-env.outputs.env_name }}"
          echo "env_variable=${{ vars.TESTDATA }}" >> $GITHUB_OUTPUT
          echo "env_secret=${{ secrets.TESTKEY }}" >> $GITHUB_OUTPUT

  deploy-front:
    needs: prepare-variables
    uses: ./.github/workflows/reusable-deploy-front.yml
    strategy:
      matrix:
        component: ["front1"]
    with:
      components: ${{ matrix.component }}
      environment-variable: ${{ needs.prepare-variables.outputs.env_variable }}
    secrets:
      environment-secret: ${{ needs.prepare-variables.outputs.env_secret }}


  deploy-backend:
    needs: prepare-variables
    uses: ./.github/workflows/reusable-deploy-backend.yml
    strategy:
      matrix:
        component: ["backend1","backend2","backend3"]
    with:
      components: ${{ matrix.component }}
      environment-variable: ${{ needs.prepare-variables.outputs.env_variable }}
    secrets:
      environment-secret: ${{ needs.prepare-variables.outputs.env_secret }}

  deploy-lambda-layer:
    needs: prepare-variables
    uses: ./.github/workflows/reusable-deploy-lambda.yml
    strategy:
      matrix:
        component: ["lambda-layer1"]
    with:
      components: ${{ matrix.component }}
      environment-variable: ${{ needs.prepare-variables.outputs.env_variable }}
    secrets:
      environment-secret: ${{ needs.prepare-variables.outputs.env_secret }}

  deploy-lambda:
    needs: [prepare-variables, deploy-lambda-layer]
    uses: ./.github/workflows/reusable-deploy-lambda.yml
    strategy:
      matrix:
        component: ["lambda1","lambda2","lambda3","lambda4","lambda5","lambda6","lambda7","lambda8","lambda9","lambda10"]
    with:
      components: ${{ matrix.component }}
      environment-variable: ${{ needs.prepare-variables.outputs.env_variable }}
    secrets:
      environment-secret: ${{ needs.prepare-variables.outputs.env_secret }}
