name: delivery

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment name to use when triggered manually'
        required: false

env:
  ENV_DEV_TEST: '["dev","test"]'
  ENV_LIVE: '["live"]'

jobs:
  prepare:
    name: Prepare environment
    runs-on: ubuntu-latest
    outputs:
      selected-environments: ${{ steps.choose_env.outputs.selected-environments }}
    steps:
      - name: Checkout (full history & tags)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Choose selected environments
        id: choose_env
        shell: bash
        run: |
          # detect if this commit is in origin/main
          if git branch -r --contains "$GITHUB_SHA" | grep -q 'origin/main$'; then
            MAIN=true
          else
            MAIN=false
          fi

          # decide whether tag has -build suffix
          if [[ "$GITHUB_REF_NAME" == *-* ]]; then
            HAS_BUILD=true
          else
            HAS_BUILD=false
          fi

          # validation: main tags must NOT have -build; non-main must have -build
          if [ "$MAIN" = true ] && [ "$HAS_BUILD" = true ]; then
            echo "ERROR: main tags must not contain -build suffix" >&2; exit 1
          fi
          if [ "$MAIN" = false ] && [ "$HAS_BUILD" = false ]; then
            echo "ERROR: non-main tags must include -build suffix" >&2; exit 1
          fi

          if [ "$HAS_BUILD" = true ]; then
            SELECTED_ENV="$ENV_DEV_TEST"
          else
            SELECTED_ENV="$ENV_LIVE"
          fi

          echo "$SELECTED_ENV"
          echo "selected-environments=$SELECTED_ENV" >> $GITHUB_OUTPUT

  delivery-backends:
    needs: prepare
    uses: ./.github/workflows/delivery-backends.yml
    with:
      environments: ${{ needs.prepare.outputs.selected-environments }}
    secrets: inherit
