name: deploy-lambdas

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name to use when triggered manually'
        required: true
        default: 'dev'
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment name to use when triggered manually'
        required: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-backend.yml
    strategy:
      matrix:
        component: ["lambda1","lambda2","lambda3","lambda4","lambda5","lambda6","lambda7","lambda8","lambda9","lambda10"]
    with:
      components: ${{ matrix.component }}
      environment: ${{ inputs.environment }}
    secrets: inherit
