name: deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment name to use when triggered manually'
        required: false

jobs:
  prepare:
    name: Prepare environment
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.determine_env.outputs.env_name }}
    steps:
      - id: determine_env
        name: Determine environment
        run: |
          echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            INPUT_ENV="${{ github.event.inputs.environment }}"
            if [ -n "${INPUT_ENV}" ]; then
              echo "env_name=${INPUT_ENV}" >> $GITHUB_OUTPUT
            else
              echo "env_name=manual" >> $GITHUB_OUTPUT
            fi
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            ENV=${TAG%%@*}
            echo "env_name=${ENV}" >> $GITHUB_OUTPUT
          else
            echo "env_name=unknown" >> $GITHUB_OUTPUT
          fi

  deploy-front:
    needs: prepare
    uses: ./.github/workflows/deploy-fronts.yml
    with:
      environment: ${{ needs.prepare.outputs.env_name }}
    secrets: inherit


  deploy-backend:
    needs: prepare
    uses: ./.github/workflows/deploy-backends.yml
    with:
      environment: ${{ needs.prepare.outputs.env_name }}
    secrets: inherit

  deploy-lambda:
    needs: prepare
    uses: ./.github/workflows/deploy-lambdas.yml
    with:
      environment: ${{ needs.prepare.outputs.env_name }}
    secrets: inherit
