name: flontend-deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment name to use when triggered manually'
        required: true
      components:
        type: string
        description: 'Components to deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Output deploy logs
        run: |
          echo "build ${{ inputs.components }}"
  deliver-deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Output deploy logs
        run: |
          echo "deliver"
          echo "component=${{ inputs.components }}, env_variable=${{ vars.TESTDATA }}, env_secret=${{ secrets.TESTKEY }}"