name: Reusable Deploy Backend

on:
  workflow_call:
    inputs:
      components:
        required: true
        type: string
      env_variable:
        required: true
        type: string
    secrets:
      env_secret:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Output deploy logs
        run: |
          echo "deliver"
          echo "component=${{ inputs.components }}, env_variable=${{ inputs.env_variable }}, env_secret=${{ secrets.env_secret }}"
  deliver:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Output deploy logs
        run: |
          echo "deliver"
          echo "component=${{ inputs.components }}, env_variable=${{ inputs.env_variable }}, env_secret=${{ secrets.env_secret }}"
  deploy-backend:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Output deploy logs
        run: |
          echo "deploy"
          echo "component=${{ inputs.components }}, env_variable=${{ inputs.env_variable }}, env_secret=${{ secrets.env_secret }}"
