name: Reusable Deploy Backend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      components:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: set_env
        name: Determine environment
        run: |
          echo "set-up step"
  deliver:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Output deploy logs
        run: |
          echo "component=${{ inputs.components }} to deploy to environment ${{ inputs.environment }}"
  deploy-backend:
    runs-on: ubuntu-latest
    needs: deliver
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Output deploy logs
        run: |
          echo "component=${{ inputs.components }} to deploy to environment ${{ inputs.environment }}"
